# Generated by Django 3.0.3 on 2020-03-25 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('sunday_open', models.TimeField(default=datetime.time(0, 0))),
                ('sunday_close', models.TimeField(default=datetime.time(0, 0))),
                ('monday_open', models.TimeField(default=datetime.time(0, 0))),
                ('monday_close', models.TimeField(default=datetime.time(0, 0))),
                ('tuesday_open', models.TimeField(default=datetime.time(0, 0))),
                ('tuesday_close', models.TimeField(default=datetime.time(0, 0))),
                ('wednesday_open', models.TimeField(default=datetime.time(0, 0))),
                ('wednesday_close', models.TimeField(default=datetime.time(0, 0))),
                ('thursday_open', models.TimeField(default=datetime.time(0, 0))),
                ('thursday_close', models.TimeField(default=datetime.time(0, 0))),
                ('friday_open', models.TimeField(default=datetime.time(0, 0))),
                ('friday_close', models.TimeField(default=datetime.time(0, 0))),
                ('saturday_open', models.TimeField(default=datetime.time(0, 0))),
                ('saturday_close', models.TimeField(default=datetime.time(0, 0))),
                ('phone', models.BigIntegerField()),
                ('rating', models.SmallIntegerField()),
                ('price', models.SmallIntegerField()),
                ('category', models.TextField()),
                ('address', models.TextField()),
                ('website', models.TextField()),
            ],
        ),
    ]
