# Generated by Django 3.0.3 on 2020-03-26 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_restaurant_roulette', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='rating',
            field=models.DecimalField(decimal_places=1, max_digits=2),
        ),
    ]
